### ISSUE TITLE
[FEAT] 생일 추가하기

### ISSUE THREAD

**Issue by hajizn-pi** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoRise#10]
## 🐲 Description

생일을 추가하는 로직을 만듭니다...

## 🧑‍💻 Todo

- [x]  정보를 받는 뷰 구성(CreateBdayView 작업 예정)
- [x] 정보 받는 함수 만들기
- [x] 정보 받고 확인

## ✏️ ETC

메모 및 전달 사항을 작성해 주세요.
