### ISSUE TITLE
[FEAT] CalendarView 구현하기 

### ISSUE THREAD

**Issue by teabag759** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoRise#23]
## 🐲 Description

CalendarView를 구현합니다 

## 🧑‍💻 Todo

- [x] 커스텀 캘린더 구현 
- [x] 선택한 일자에 생일 일자가 있으면 dot으로 표현 
- [x] 선택한 일자에 해당하는 생일자의 카드 : 이름, 오늘로부터 며칠 남았는지, 이미지, 태그에 따른 색 변경 
- [x] 상단에 캘린더에서 선택한 일자 표현 
- [x] 카드를 밀면 delete 되도록 
- [x] delete 버튼을 누르면 alret 되도록 

## ✏️ ETC

시간이 나면 구현해야 할 것 
- [x] 이전, 다음 달로 이동 
- [ ] datepicker 누르면 해당 일자로 이동하도록
