### ISSUE TITLE
[Feat] 캘린더 뷰에서 수정뷰로 넘어가기

### ISSUE THREAD

**Issue by hajizn-pi** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoRise#27]
## 🐲 Description

캘린더뷰의 리스트를 클릭하면 수정 뷰로 넘어가는 코드를 짤 예정입니다.

## 🧑‍💻 Todo

- [x] 리스트 버튼 화
- [x] 리스트 클릭 시 정보 넘어갈 수 있도록 하기
- [x] 수정뷰에서 이전에 작성한 내용 가져오기
- [x] 내용 수정 가능
- [x] 저장 기능

## ✏️ ETC

메모 및 전달 사항을 작성해 주세요.
