### ISSUE TITLE
[FIX] SaveBdayView 오류 수정

### ISSUE THREAD

**Issue by hajizn-pi** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoRise#45]
## 🐲 Description

생일 저장 뷰를 수정합니다. 

## 🧑‍💻 Todo

- [ ]  이미지 피커 눌렀을 때 이미지 등록되도록
- [x]  이름 - 키보드 필드 내려가기
- [x]  생일 날짜 눌렀을 때 bottomSheet 뜨도록
- [x]  양력/음력 로직
- [ ]  태그 : 가족, 친구(기본)
    - [x]  태그 이름 입력 + 색상 지정 (한정된 컬러 - 10개)
- [ ]  알림 삭제 확인 - 알림 등록한 후 사용자 정보 삭제시 없어지는 지 확인하기
- [x]  bottomSheet
    - [x]  Picker위에 음력/양력 여부
    - [x]  picker 한글 처리
    - [x]  사용자가 입력한 날짜 (yyyy.MM.dd)

## ✏️ ETC

도라이즈 진심 파이팅
