### ISSUE TITLE
[FEAT] CalendarView 버그 수정 및 기능 추가

### ISSUE THREAD

**Issue by teabag759** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoRise#46]
## 🐲 Description

CalendarView에서 정보가 삭제되어도 data가 있음을 표시하는 dot이 지워지지 않는 오류를 해결하고 
추가된 기능들을 구현합니다.

## 🧑‍💻 Todo

- [ ]  생일 삭제시 dot이 지워지지 않는 오류 해결 
- [ ]  오늘의 날짜, 네비게이션 타이틀, 달력 일자 표시 구현 
- [ ]  CardView를 List로 변환 
- [ ]  생일이 없을 때는 텍스트가 나타날 수 있도록
- [ ]  TabBar 구현

[기타]
- [ ]  Calendar 넘어갈 때 Swipe gesture 구현하기(상호 간섭 확인 후) 

## ✏️ ETC

TabBar 구현시 View 간섭이 우려됩니다
