### ISSUE TITLE
[FEAT] UpcomingView 기능 추가 및 뷰 수정

### ISSUE THREAD

**Issue by bohemio1234** [DeveloperAcademy-POSTECH/2024-MacC-M06-DoRise#47]
## 🐲 Description

upcomingview 뷰 수정, 기능 추가 

## 🧑‍💻 Todo

- [x]  오늘의 날짜 뜨게 하기 - 요일(노랑색), 날짜
- [x]  날짜 옆에 캘린더 넘어가는 버튼 있어야함.
- [x]  가장 가까운 생일 카드 만들기
    - [x]  이름, 이미지, 생일(MM.dd(요일)), D-day
    - [x]  누르면 PersonalDetailView
    - [x]  동일한 날짜의 생일이 여러 개 있는 경우 CarouselView 형태
- [x]  곧 생일이에요
    - [x]  CardView
        - [x]  이름, 이미지, 태그, D-day, 생일
        - [x]  바탕색상 → main Color , 태그 배경에 태그에 알맞는 색상 입히기
- [x]  탭바 추가
    - [x]  Home - 홈, Person - 친구, Gift - 선물

## ✏️ ETC

할 수 있다. 해야 한다
